---
- hosts: localhost
  tasks:
    - name: install homebrew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      become: false
      with_items:
        - multipass
        - visual-studio-code
        - vlc
    - name: install homebrew taps
      community.general.homebrew_tap:
        name: "{{ item }}"
      become: false
      with_items:
        - atombender/ktail
    - name: install homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
      become: false
      with_items:
        - azure-cli
        - bandit
        - colima
        - cmake
        - docker
        - docker-compose
        - docker-buildx
        - dockle
        - gh
        - gifski
        - git
        - git-town
        - gpg
        - helm
        - hugo
        - jq
        - k3d
        - kubectl
        - kubectx
        - kumactl
        - nvm
        - python3
        - pipenv
        - shellcheck
        - speedtest-cli        
        - task
        - trivy
        - vim
        - yarn
        - yq
