---
- hosts: localhost
  tasks:
    - name: update brew itself
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
    - name: set java folder permissions
      ansible.builtin.command: chown desktophero /Library/Java/JavaVirtualMachines
    - name: install homebrew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: installed
        accept_external_apps: true
      become: false
      with_items:
        - devtoys
        - fig
        - google-chrome
        - insomnia
        - iterm2
        - maccy
        - multipass
        - rectangle
        - powershell
        - visual-studio-code
        - vlc
    - name: install homebrew taps
      community.general.homebrew_tap:
        name: "{{ item }}"
      become: false
      with_items:
        - atombender/ktail
    - name: install homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
      become: false
      with_items:
        - act
        - atombender/ktail/ktail
        - azure-cli
        - bandit
        - colima
        - cmake
        - docker
        - docker-compose
        - docker-buildx
        - docker-credential-helper
        - goodwithtech/r/dockle
        - gh
        - gifski
        - git
        - git-town
        - gpg
        - helm
        - hugo
        - java
        - jq
        - k3d
        - kubectl
        - kubectx
        - maven
        - nvm
        - openjdk@20
        - python3
        - pipenv
        - shellcheck
        - speedtest-cli        
        - task
        - tfenv
        - trivy
        - vim
        - yarn
        - yq
    - name: setup symlink for openjdk
      file:
        src: /opt/homebrew/opt/openjdk/libexec/openjdk.jdk
        dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
        state: link
  roles: 
    - role: gantsign.visual-studio-code-extensions
      users:
        - username: desktophero
          visual_studio_code_extensions:
            - timonwong.shellcheck
            - github.vscode-github-actions
            - me-dutour-mathieu.vscode-github-actions
            - vscodevim.vim
            - sldobri.bunker
            - shd101wyy.markdown-preview-enhanced
