---
- hosts: localhost
  tasks:
    - name: update brew itself
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
    - name: install homebrew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      become: false
      with_items:
        - devtoys
        - fig
        - maccy
        - multipass
        - rectangle
        - visual-studio-code
        - vlc
    - name: install homebrew taps
      community.general.homebrew_tap:
        name: "{{ item }}"
      become: false
      with_items:
        - atombender/ktail
    - name: install homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
      become: false
      with_items:
        - act
        - azure-cli
        - bandit
        - colima
        - cmake
        - docker
        - docker-compose
        - docker-buildx
        - docker-credential-helper
        - dockle
        - gh
        - gifski
        - git
        - git-town
        - gpg
        - helm
        - hugo
        - java
        - jq
        - k3d
        - kubectl
        - kubectx
        - maven
        - nvm
        - openjdk@20
        - python3
        - pipenv
        - shellcheck
        - speedtest-cli        
        - task
        - trivy
        - vim
        - yarn
        - yq
    - name: setup symlink for openjdk
      file:
        src: /opt/homebrew/opt/openjdk/libexec/openjdk.jdk
        dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
        state: link
